### ISSUE TITLE
使用该sdk报Caused by: java.lang.ClassNotFoundException: com.aliyuncs.auth.AlibabaCloudCredentials

### ISSUE THREAD

**Issue by liumx95** [aliyun/alibabacloud-encryption-sdk-java#11]
Exception in thread "main" java.lang.NoClassDefFoundError: com/aliyuncs/auth/AlibabaCloudCredentials
	at BasicEncryptionExample.main(BasicEncryptionExample.java:20)
Caused by: java.lang.ClassNotFoundException: com.aliyuncs.auth.AlibabaCloudCredentials
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 1 more

**Comment by simonbennet** [comment]
add `aliyun-java-sdk-core` to your pom.xml

```xml
  <dependency>
      <groupId>com.aliyun</groupId>
      <artifactId>aliyun-java-sdk-core</artifactId>
  </dependency>
```
